Sonchau/katsu update
CanDIG/CanDIGv2 pull request #232
Opened 2023-05-16 16:57 UTC by SonQBChau

What's new:
- This PR updates katsu tests to use v2 and fix the broken test integration

How to test:
- Make sure submodules katsu on `develop` and OPA on `main` and up-to-date
```
make clean-all
make build-all
make init-conda
conda activate candig
make build-all
make test-integration
```

2023-05-18 18:51 UTC, daisieh requested changes, later dismissed

2023-05-18 18:51 UTC, daisieh commented on etc/tests/test_integration.py
I can't tell if there are any changes to the katsu tests besides just updating the paths. Are you sure you don't want to add some more robust tests here?

2023-05-18 18:55 UTC, daisieh commented on etc/tests/test_integration.py
Also, I would like the katsu tests to ingest at least a few full test samples so that we can connect them to htsget test objects and test that.

2023-05-18 19:11 UTC, SonQBChau commented on etc/tests/test_integration.py
I would like to do it in another PR and keep this clean because there are so much debugging going now

2023-05-18 20:23 UTC, daisieh approved these changes
This looks fine

2023-05-19 04:14 UTC, yavyx commented
`test_katsu_users`  is not passing for me:
`FAILED etc/tests/test_integration.py::test_katsu_users[CANDIG_NOT_ADMIN-SYNTHETIC-1-SYNTHETIC-2] - KeyError: 'results'`

2023-05-23 15:24 UTC, SonQBChau commented
can you post the full log? KeyError: results suggests one of the services may not working

2023-05-24 00:27 UTC, yavyx commented
After rebuilding everything with the new branches I'm getting the following failures:

**test_setup_katsu**
```
 if response.status_code >= 400:
            errors = response.json()["error during ingest_donors"]
>           assert (
                "code='unique'" in errors and "donor_id" in errors
            )  # this means that the error was just that the program IDs already exist
E           assert ("code='unique'" in "[{'gender': [ErrorDetail(string='This field is required.', code='required')], 'sex_at_birth': [ErrorDetail(string='Th...='required')], 'date_alive_after_lost_to_followup': [ErrorDetail(string='This field is required.', code='required')]}]")
etc/tests/test_integration.py:359: AssertionError
```

**test_katsu_users**
```
>       assert dataset in donors
E       AssertionError: assert 'SYNTHETIC-2' in []
etc/tests/test_integration.py:399: AssertionError
```
```
>       assert dataset in donors
E       AssertionError: assert 'SYNTHETIC-1' in []

etc/tests/test_integration.py:399: AssertionError
```

2023-05-24 00:28 UTC, yavyx commented
Katsu logs:
```
Bad Request: /v2/ingest/programs
[24/May/2023 00:21:46] [django.request] WARNING: Bad Request: /v2/ingest/programs
[24/May/2023 00:21:46] "POST /v2/ingest/programs HTTP/1.1" 400 201
Bad Request: /v2/ingest/donors
[24/May/2023 00:21:46] [django.request] WARNING: Bad Request: /v2/ingest/donors
[24/May/2023 00:21:46] "POST /v2/ingest/donors HTTP/1.1" 400 3593
[24/May/2023 00:21:46] "GET /v2/authorized/programs/ HTTP/1.1" 200 160
[24/May/2023 00:21:46] "GET /v2/authorized/donors/ HTTP/1.1" 200 52
[24/May/2023 00:21:46] "GET /v2/authorized/programs/ HTTP/1.1" 200 160
[24/May/2023 00:21:46] "GET /v2/authorized/donors/ HTTP/1.1" 200 52
```

2023-05-24 15:48 UTC, SonQBChau commented
I forget to include this in the test instructions, you need to change the test data to my branch as well. At line 348:
```
test_loc = "https://github.com/CanDIG/katsu/blob/sonchau/part_32/chord_metadata_service/mohpackets/data/small_dataset/synthetic_data/Donor.json"
```

2023-05-29 19:22 UTC, yavyx approved these changes
OPA and katsu integration tests are passing

2023-05-30 20:41 UTC, jman005 commented
OPA/Katsu tests pass on my system.

2023-05-30 20:41 UTC, jman005 approved these changes
OPA/Katsu tests pass on my system.

2023-05-30 22:36 UTC, merged