DIG-1273: Add more endpoints to the Tyk test, and add a timeout
CanDIG/CanDIGv2 pull request #270
Opened 2023-08-01 19:51 UTC by OrdiNeu

[Jira ticket](https://candig.atlassian.net/browse/DIG-1273)

This PR makes sure Tyk is able to communicate with all endpoints, rather than just HTSGet.

**To test**:
Setup the entire stack, as usual, then:
1. Check that the Test_Tyk works if the entire setup is working, and then:
2. Fails if either OPA, Federation, HTSGet, or Katsu are down

You can run this specific test with `python settings.py; source env.sh; pytest ./etc/tests -k "Test_Tyk"`, or by running all integration tests (make test-integration).

2023-08-03 00:21 UTC, daisieh requested changes
Maybe add a print so you can see which endpoint failed?

2023-08-09 20:42 UTC, OrdiNeu commented
@daisieh 
> Maybe add a print so you can see which endpoint failed?

Fixed :heavy_check_mark:

2023-08-09 20:45 UTC, OrdiNeu commented
Unsure what's causing that build failure (conda failing to install??), checking...

2023-08-10 00:53 UTC, daisieh approved these changes
Looks good!

2023-08-15 14:54 UTC, OrdiNeu commented
No idea why the check failed again -- it's failing on a completely different test. Going to try retriggering

2023-08-15 16:27 UTC, merged