Increase healthcheck timeout for metadata-db, and fix the healthcheck.
CanDIG/CanDIGv2 pull request #531
Opened 2024-04-10 14:13 UTC by OrdiNeu

# Ticket(s)
[DIG-1571](https://candig.atlassian.net/browse/DIG-1571)

# Description
This both fixes the command being used to check metadata-db, and increases the timeout for it

# To test
1. Check that metadata-db still runs, and that the healthcheck reports healthy initially.
2. `docker exec -it candigv2_katsu_1 bash`
3. `export PGPASSWORD=$(< /run/secrets/metadata_db_secret)`
4. `psql -h metadata-db -U "admin" -d genomic`
5. `DROP DATABASE metadata;`
6. Exit out. Healthcheck should now be "unhealthy"

[DIG-1571]: https://candig.atlassian.net/browse/DIG-1571?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-04-10 14:19 UTC, lilyyangyi301 approved these changes
LGTM!

2024-04-10 14:30 UTC, lilyyangyi301 requested changes
After testing, the health check still reports 'healthy' but I can see this error inside the container log `2024-04-10 10:27:12 2024-04-10 14:27:12.160 UTC [492] FATAL:  database "metadata" does not exist`

2024-04-10 14:40 UTC, lilyyangyi301 approved these changes
Behave as expected during testing. LGTM!

2024-04-11 23:35 UTC, mshadbolt approved these changes
Tried the steps described and worked for me

2024-04-12 14:03 UTC, merged