Conda fixes + Vagrant libvirt addition
CanDIG/CanDIGv2 pull request #97
Opened 2021-09-29 19:26 UTC by amanjeev

Minor fixes to run conda and a section for libvirt in  Vagrantfile.

Asking this to be merged into hotfix/post-auth-merge-fixes since I started with that branch.

2021-10-05 19:41 UTC, shaikh-rashid commented on Makefile
> +		&& conda create -y -n $(VENV_NAME) python=$(VENV_PYTHON) pip=$(VENV_PIP)
should still use $(CONDA) in order to ensure specified conda bin in $(DIR)  is being called. There are weird edge cases where  external conda bins could exist in PATH ahead of the newly sourced conda

2021-10-05 19:43 UTC, shaikh-rashid commented on Makefile
> +	source $(DIR)/bin/miniconda3/etc/profile.d/conda.sh && source /home/vagrant/.bashrc \
should not hardcode sourcing of bashrc path as this may not exist in all cases (ie. non vagrant deployments)

2021-10-05 19:44 UTC, shaikh-rashid commented on Makefile
> +	source $(DIR)/bin/miniconda3/etc/profile.d/conda.sh && source /home/vagrant/.bashrc \
See previous comments regarding conda path and sourcing

2021-10-05 19:50 UTC, shaikh-rashid requested changes
These changes are needed but only in the Vagrant context. I would suggest modifying the PR so that these changes are in the Vagrantfile or the provision.sh. I will conduct a test on Mordor to verify your PR in an HPC environment.

2021-10-06 12:42 UTC, amanjeev commented on Makefile
> +	source $(DIR)/bin/miniconda3/etc/profile.d/conda.sh && source /home/vagrant/.bashrc \
I tried removing all instances of hardcoded conda but this remained.  I will test this one our in a bit.

2021-10-06 12:45 UTC, amanjeev commented on Makefile
> +	source $(DIR)/bin/miniconda3/etc/profile.d/conda.sh && $(CONDA) init
same here

2021-10-06 22:51 UTC, amanjeev commented on Makefile
> +		&& conda activate $(VENV_NAME) \
@shaikh-rashid  I could remove all instances of bashrc and give the conda settings a common variable.  what I could not do what this line here where to activate you have to use `conda` in the PATH rather than the full path using `$(CONDA)`. It seems to work on my virtualbox stuff and I would love if you can try this version on the mordor hpc please.

2021-10-18 18:58 UTC, amanjeev commented
Once this is tested by @daisieh and @shaikh-rashid and all looks good we will merge, leaving HPC behind.

2021-10-21 01:09 UTC, amanjeev commented
@shaikh-rashid @daisieh I am not sure if there is anything left to do here based on the discussion on Monday. Can we merge this?

2021-10-21 11:21 UTC, ljdursi commented
We really need the authentication (and next, authorization) working.  Merge this and if there are new tickets that need to be created for any changes, they can be worked on in parallel with the authorization work.

2021-10-22 20:09 UTC, amanjeev commented
Decided to merge this after standup today.

2021-10-22 20:09 UTC, merged